version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
     - '3000:27017'
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
     - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - '8081:8081'
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
     - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
     - ME_CONFIG_MONGODB_SERVER=mongodb
     - ME_CONFIG_MONGODB_PORT=27017

volumes:
  mongo-data:
    driver: local